### ISSUE TITLE
Tracking for RPC Support

### ISSUE THREAD

**Issue by InsidiousMind** [ethdbg/edb#21]
- [ ] Ganache : Not fully supported. Some Ganache Functions return types that web3 does not expect (ie, 0x00 for eth_getStorageAt, which rust-web3 expects to be a 64-character long string)
- [ ] Parity Dev Mode: Currently Testing
- [ ] Geth Test/Dev Mode: Currently Testing
